/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectallocationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 91892
 */
public class newProfessorDetails extends javax.swing.JFrame {

    /**
     * Creates new form newProfessorDetails
     */
    public newProfessorDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        pq = new javax.swing.JTextField();
        combo2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        combo3 = new javax.swing.JComboBox<>();
        combo4 = new javax.swing.JComboBox<>();
        professorSubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Professor Sign Up");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 45));

        pname.setText("Name");
        jPanel2.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 102, 179, 31));

        pq.setText("Qualifications");
        pq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pqActionPerformed(evt);
            }
        });
        jPanel2.add(pq, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 179, 59));

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel2.add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 218, 203, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Knowledge Domain");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 108, 175, -1));

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel2.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 167, 203, 31));

        combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel2.add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 267, 203, 31));

        combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel2.add(combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 316, 203, 31));

        professorSubmit.setText("Submit");
        professorSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(professorSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 397, 98, 31));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 397, 98, 31));

        username.setText("Create Username");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 218, 179, 31));

        p1.setText("Create Password");
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 271, 179, 27));

        p2.setText("Comfirm Password");
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 316, 179, 31));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\91892\\Desktop\\Public\\DBMS_JAVA Project\\sky2.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pqActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login l = new login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void professorSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorSubmitActionPerformed
        String name = pname.getText();
        String qualification = pq.getText();
        String uname = username.getText();
        String pass = p1.getText();
        String passcom = p2.getText();
        String area1 = (String)combo1.getSelectedItem();
        String area2 = (String)combo2.getSelectedItem();
        String area3 = (String)combo3.getSelectedItem();
        String area4 = (String)combo4.getSelectedItem();
        
//        System.out.println(name+" "+course+" "+semString+" "+stream+" "+area1+" "+area2+" "+area3+" "+area4);
        if(pass.equals(passcom)){
          try{
            //Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projectallocationsystem","root","root");
            Statement stml=con.createStatement();
            String sql1 = "insert into professor(pname,qualifications,area1,area2,area3,area4,username,passwordd) values('"+name+"','"+qualification+"','"+area1+"','"+area2+"','"+area3+"','"+area4+"','"+uname+"','"+pass+"')";
            stml.executeUpdate(sql1);
            JOptionPane.showMessageDialog(null,"Sign in successfull");
        }
        catch(Exception e){
            System.out.println(e);
        }  
        }
        else{
            JOptionPane.showMessageDialog(null,"Password and Comfirmation passwords are different");   
        }
        
    }//GEN-LAST:event_professorSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pq;
    private javax.swing.JButton professorSubmit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
