/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectallocationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 91892
 */
public class NewStudentDetails extends javax.swing.JFrame {

    /**
     * Creates new form NewStudentDetails
     */
    public NewStudentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tstream = new javax.swing.JTextField();
        Tname = new javax.swing.JTextField();
        Tcourse = new javax.swing.JTextField();
        Tsem = new javax.swing.JTextField();
        Combo2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JComboBox<>();
        Combo3 = new javax.swing.JComboBox<>();
        Combo4 = new javax.swing.JComboBox<>();
        SubmitBotton = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        passcomf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Sign UP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 45));

        Tstream.setText("BTech Stream/ Plus One-Two Stream");
        jPanel1.add(Tstream, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 31));

        Tname.setText("Name");
        jPanel1.add(Tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 209, 31));

        Tcourse.setText("Course");
        jPanel1.add(Tcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 209, 31));

        Tsem.setText("Semester");
        jPanel1.add(Tsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 209, 31));

        Combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel1.add(Combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 203, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Interested Areas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 175, -1));

        Combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel1.add(Combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 203, 31));

        Combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel1.add(Combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 203, 31));

        Combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artificial Inteligence", "ML", "Deep Learning", "Quantum Computing", "NLP", "IOT", "Cloud Computing", "Bioinformatics", "Digital Image Processing", "Computer Vision" }));
        jPanel1.add(Combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 203, 31));

        SubmitBotton.setText("Submit");
        SubmitBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBottonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 98, 31));

        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        jPanel1.add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, 31));

        username.setText("Create Username");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 209, 31));

        pass.setText("Create Password");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 209, 30));

        passcomf.setText("Comfirm Password");
        jPanel1.add(passcomf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 209, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\91892\\Desktop\\Public\\DBMS_JAVA Project\\sky2.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 807, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        login l = new login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BbackActionPerformed

    private void SubmitBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBottonActionPerformed
        String name = Tname.getText();
        String course = Tcourse.getText();
        String semString = Tsem.getText();
//        int sem = Integer.parseInt(semString);
        String stream = Tstream.getText();
        String area1 = (String)Combo1.getSelectedItem();
        String area2 = (String)Combo2.getSelectedItem();
        String area3 = (String)Combo3.getSelectedItem();
        String area4 = (String)Combo4.getSelectedItem();
        String password = pass.getText();
        String usernamee = username.getText();
        String passComfirm = passcomf.getText();
        if(password.equals(passComfirm)){
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projectallocationsystem","root","root");
            Statement stml=con.createStatement();
            String sql1 = "insert into student(sname,course,semester,BtechOrPlustwo,topic1,topic2,topic3,topic4,username,passwords) values('"+name+"','"+course+"','"+semString+"','"+stream+"','"+area1+"','"+area2+"','"+area3+"','"+area4+"','"+usernamee+"','"+password+"')";
            stml.executeUpdate(sql1);
            JOptionPane.showMessageDialog(null,"Sign in successfull");
        }
        catch(Exception e){
            System.out.println(e);
        }  
        }
        else{
            JOptionPane.showMessageDialog(null,"Password and Comfirmation password are different");
        }
//        System.out.println(name+" "+course+" "+semString+" "+stream+" "+area1+" "+area2+" "+area3+" "+area4);
        
        
    }//GEN-LAST:event_SubmitBottonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JComboBox<String> Combo2;
    private javax.swing.JComboBox<String> Combo3;
    private javax.swing.JComboBox<String> Combo4;
    private javax.swing.JButton SubmitBotton;
    private javax.swing.JTextField Tcourse;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tsem;
    private javax.swing.JTextField Tstream;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField passcomf;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
